# AA-UTE 2026

## Práctica 0 - Python, manejo de datos y gráficas con librerías

### Objetivos:
En esta práctica se introducen algunas herramientas de manejo de datos en Python que van a ser útiles para las prácticas del curso


### Trabajo a realizar

A lo largo del notebook encontrarán las siguientes palabras claves:

* **\# COMPLETAR**  -> indica que se requiere completar el código. 
  
  
* **\# EXPERIMENTAR** -> indica que la celda contiene código funcional que permite experimentar variando parámetros de las funciones. Es posible, si lo requiere la experimentación, duplicar la celda y realizar los cambio que sean de interés en el código.
  
  
* **\# DISCUTIR** -> se espera una discusión de los experimentos realizados y/o de las preguntas formuladas
  
  
  
* **\# RESPONDER** -> se espera una respuesta a preguntas concretas

## Parte 1 - Definición de los módulos a usar

In [1]:
# En esta celda se definen los modulos que se van a usar en el notebook 

import numpy as np  # paquete matemático para el manejo de arreglos/arrays
import pandas as pd # paquete de manejo de datos en dataframes o series
import matplotlib.pyplot as plt # paquete para realizar gráficos

# FORMAS DE VER LAS GRAFICAS --------------------
# ELEGIR UNA DE LAS OPCIONES Y DES-COMENTAR (sacar # de la linea)
# ----------------
# a) graficas en línea  entre las celdas (no interactivo)
#%matplotlib inline
# ---------------- 
# b) graficas en línea  entre las celdas (interactivo)
# %matplotlib notebook
# ----------------
# c) graficas en ventanas externas (abre una ventana por cada figura)
# %matplotlib
# ----------------
# d) Si se usa "jupyter lab" en lugar de "jupyter notebook" usar %matplotlib widget en lugar de %matplotlib notebook 
#    Si se usa vscode usar también %matplotlib widget en lugar de %matplotlib notebook 
# requiere instalar el modulo "ipympl". Ver https://stackoverflow.com/questions/51922480/javascript-error-ipython-is-not-defined-in-jupyterlab#56416229
# %matplotlib widget
#---------------------------------------------------

## Parte 2 - Creación de arrays en numpy [(referencia)](https://cs231n.github.io/python-numpy-tutorial/#arrays)

In [2]:
print('-------------------------------------------------')
# Crear un array unidimensional
a = np.array([10, 20, 30, 40, 50])
print('array a')
# Imprimir el tipo de dato
print(a.dtype)
# Imprimir las dimensiones del array
print(a.shape)    


print('-------------------------------------------------')
# Crear un array bidimensional
b = np.array([[1.5, 2.3, 3], [4.44, 5.67, 6.88]])
print('array b')
print(b.dtype)
print(b.shape)
print(b)

print('-------------------------------------------------')
# Crear un array de un tipo de datos específico
c = np.array([[1,2,3],[4,5,6]], dtype = np.uint8)
print('array c:  tipo:',c.dtype)


print('-------------------------------------------------')
# Existen distintas funciones que permiten crear arrays en numpy
# Ej. np.ones(...), np.zeros(...), np.random.rand(...)
z = np.zeros((3,4))
print('array z\n', z)

print('-------------------------------------------------')


-------------------------------------------------
array a
int64
(5,)
-------------------------------------------------
array b
float64
(2, 3)
[[1.5  2.3  3.  ]
 [4.44 5.67 6.88]]
-------------------------------------------------
array c:  tipo: uint8
-------------------------------------------------
array z
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------------------------------------------


In [ ]:
# EXPERIMENTAR Duplicar la celda de arriba y realizar pruebas  


Observar los diferentes **formatos** para **incluir variables** en strings. 

En [este enlace](https://www.pythoncheatsheet.org/cheatsheet/string-formatting) se pueden encontrar más ejemplos.

In [3]:
np_array = b

# string con formato 
info = 'tipo:{}, dimensión:{}, tamaño:{}'.format(np_array.dtype, np_array.ndim, np_array.shape)
# otra forma de generar string con formato
misma_info = f'tipo:{np_array.dtype}, dimensión:{np_array.ndim}, tamaño:{np_array.shape}'

print(np_array)
print('---------------------------------------------')
print(info)
print('---------------------------------------------')
print(misma_info)
print('---------------------------------------------')
print('¿Los strings son iguales?', info==misma_info)


[[1.5  2.3  3.  ]
 [4.44 5.67 6.88]]
---------------------------------------------
tipo:float64, dimensión:2, tamaño:(2, 3)
---------------------------------------------
tipo:float64, dimensión:2, tamaño:(2, 3)
---------------------------------------------
¿Los strings son iguales? True


[Broadcast en arrays](https://cs231n.github.io/python-numpy-tutorial/#broadcasting)

In [ ]:
# Se pueden realizar operaciones entre números y arrays 
# con el broadcast automático de numpy

print('array z:\n',z)  
print('------------------')

print('array z + 1:\n',z + 1)   # sumar un número al array
print('------------------')

print('2*(z + 1):\n',2*(z + 1))   # sumar un número al array y luego multiplicar por 2
print('------------------')
# El broadcast no funciona siempre:
x = np.ones((2,3))
print(f'array z de tamaño {z.shape}:\n',z)
print('------------------')
print(f'array x de tamaño {x.shape}:\n',x)
print('------------------')
print('Ver el error que produce sumar ambos arrays (x + z) de tamaño distinto:')
x + z

In [ ]:
# Tambien existe el broadcast entre vectores y arrays, 
# siempre y cuando que coincidan con el tamaño en una dimensión

z = np.zeros((3,4))

y1 = np.ones(4) # por defecto crea un vector fila
y2 = np.ones((3,1))
print('------------------')
print(f'Array z de tamaño {z.shape}:\n',z)
print('------------------')
print(f'Sumarle a z un vector fila {y1.shape}:\n', z + y1)
print('------------------')
print(f'Sumarle a z un vector columna {y2.shape}:\n', z + y2)

In [ ]:
# EXPERIMENTAR con otras funciones como 
# np.arange(...), np.random.rand(...), np.random.randint(...), np.eye(...) 

# Tip de jupyter notebook: SHIFT-TAB cuando el cusor está sobre una función muestra la ayuda

## Parte 3 - Acceso a los datos de un array
El acceso en cada dimensión sigue el esquema [desde(incluido) : hasta(excluido) : paso]   
Si no se especifica 'desde' entonces equivale a 'desde el índice 0'  
Si no se especifica 'hasta' entonces equivale a 'hasta el último (en el sentido que dictamine 'paso')'  
El 'paso' por defecto es 1



In [ ]:
print('=================================================')
print('b')
print(b)
print('-------------------------------------------------')
# acceder a los elementos de un array
print('b[0, 0] b[0, 1] b[1, 0]')
print(b[0, 0], b[0, 1], b[1, 0])   

print('-------------------------------------------------')
# acceder a una columna de b
print('Columna 1 de b')
print(b[:,1])


print('=================================================')
print('a')
print(a)
print('-------------------------------------------------')
# acceder al primer elemento de a
print(a[0])
# acceder a los dos primeros elementos de a
print(a[:2])
# acceder al último elemento de a
print(a[-1])
# acceder a los elementos de a pero saltando de a dos
print(a[::2])
# acceder a los elementos de a pero en orden invertido
print(a[::-1])


print('=================================================')
print('---vista y copia---------------------------------')
print('b inicial')
print(b)
print('-------------------------------------------------')

g = b[:,1]  # g es una vista de una columna de b
print(g)    # 
print(b)
g[0] = np.random.randint(100)  # cambiamos el primer elemento de g
print(g)
print(b)    # y vemos que b también cambió ->  SON LOS MISMOS DATOS !!

h = b[:,2].copy()  # h es una copia de una columna de b. SI cambiamos h, no va a cambiar b
print(h)
h[1] = np.random.randint(100)
print(h)
print(b)



In [ ]:
# EXPERIMENTAR Duplicar la celda de arriba y realizar pruebas 
# de distintas formas de acceder y/o modificar los elementos de un array  


In [ ]:
# EXPERIMENTAR
# tratar de predecir la salida antes de correr cada celda
# para correr, descomentar el código quitando las comillas triples

'''
x = np.arange(21,54,2)
print(x)
'''

In [ ]:
'''
y = x[2:5]
print(y)
'''

In [ ]:
'''
y = x[-1::-1]
print(y)
'''

In [ ]:
'''
b = np.array([[1,2,3],[4,5,6]])
print(b)

y = b[:,1]
print(y)

y = b[:,-1::-1]
print(y)
'''

## Parte 4 - Crear arrays y graficar

En esta parte se utilizará la biblioteca _matplotlib_ para graficar arreglos. A modo de ejemplo se propone:

1. Crear un vector de tiempos entre 0 y 1 de largo N
1. Crear arrays de N muestras con las señales `seno` y `coseno` ( _np.sin() , np.cos()_ ).
1. Graficar ambas funciones juntas (se sugiere usar las funciones `plt.figure()`, `plt.plot()`, `plt.title()`, `plt.legend()`, `plt.xlabel()` y `plt.ylabel()`).

Puede ser de utilidad [esta referencia](https://cs231n.github.io/python-numpy-tutorial/#matplotlib) para el creado de las gráficas.


In [ ]:
N = 100
f = 2
# Array de "tiempo" con N números equiespaciados entre 0 y 1
t = np.linspace(0,1,N)

# Obtener los valores de seno y coseno para esos tiempos
sine = np.sin(2 * np.pi * f * t)
cosine = np.cos(2 * np.pi * f * t)

# Iniciar nueva figura e indicar parámetro de tamaño (figsize)
plt.figure(figsize=(8,2)) # Variar los valores de figsize (p.ej. (15,4), (10,10), (5,20))

plt.title("Función $sin (2 \pi ft)$") # Título de la gráfica

###########################################
### COMPLETAR: graficar la función seno ###
###########################################

plt.grid() # Agregar grilla

plt.show()

In [ ]:
# Graficar seno y coseno juntos en una misma gráfica
plt.figure(figsize=(8,2))
plt.title("Funciones trigonométricas")

#############################################
### COMPLETAR: graficar seno y coseno con ###
###   los valores del vector t en eje x   ###
#############################################

plt.xlabel('Tiempo (s)')
plt.legend() # Activar legenda de gráficas (ubicación 'best' por defecto. Probar 'upper left', 'lower right', 'center', etc)
plt.grid() 
plt.show()

Realizar, usando [`subplots`](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subplots_demo.html), cuatro gráficas de la función seno representada: 
1. con lineas continuas 
2. con lineas discontinuas
3. con puntos         
4. con punteo y lineas continuas

El `subplot` debe contener dos filas y dos columnas

In [ ]:
# Cantidad de muestras
N = 100

f = 2
t = np.linspace(0,1,N)
sine = np.sin(2*np.pi*f*t)



fig, ax = plt.subplots(nrows= ,ncols=   # Indicar cuántas filas y columnas de gráficas hay
                       ,figsize=(10,4)) 

####################################
### COMPLETAR: graficar subplots ###
####################################

plt.tight_layout() # ajustar posición de las imágenes
plt.show()

¿Qué pasa si cambiamos en la última celda $N=20$ ó $N=10$? ¿Sigue siendo la función seno?

## Parte 5 - Operaciones 


In [ ]:
# Fijar la "semilla" para volver a reproducir resultados aleatorios
np.random.seed(789)   #descomentar para chequear los resultados, comentar para que p cambie en cada corrida

p = np.random.rand(5,3)

print('-------------------------------------------------------------')
print('Arreglo p: \n', p)

# calcular la media de todos los elementos de p:   0.48544143187616673
media_p =  # COMPLETAR
print('-------------------------------------------------------------')
print('Promedio de p:\n', media_p)


# calcular la media de las columnas de p.          [0.54815742 0.39199966 0.51616722]
media_p_col = # COMPLETAR
print('-------------------------------------------------------------')
print('Promedio por columnas de p:\n', media_p_col)


# calcular la media de las filas de p.             
# [0.44912027 0.78623868 0.04879567 0.37839235 0.58661954 0.32941742 0.2934381  0.51920083 0.71125536 0.75193609]
media_p_row = # COMPLETAR
print('-------------------------------------------------------------')
print('Promedio por filas de p:\n', media_p_row)




Replicar la celda anterior pero agregando el argumento `keepdims` en valor **True**. ¿Qué hace esto?

In [ ]:
# Fijar la "semilla" para volver a reproducir resultados aleatorios
np.random.seed(789)   #descomentar para chequear los resultados, comentar para que p cambie  en cada corrida

p = np.random.rand(5,3)

print('-------------------------------------------------------------')
print('Arreglo p: \n', p)

# calcular la media de todos los elementos de p:
media_p = # COMPLETAR
print('-------------------------------------------------------------')
print('Promedio de p:\n', media_p)


# calcular la media de las columnas de p.       
media_p_col = # COMPLETAR
print('-------------------------------------------------------------')
print('Promedio por columnas de p:\n', media_p_col)


# calcular la media de las filas de p.             
media_p_row = # COMPLETAR
print('-------------------------------------------------------------')
print('Promedio por filas de p:\n', media_p_row)




## Parte 6 - Funciones
Definir una función que realice una suma ponderada entre dos arreglos.   
La función recibe dos arrays y dos pesos. Dentro de la función se chequea que los dos arrays sean de la mismas dimensiones, se realiza la suma ponderada y se devuelve el array resultado. En caso que no coincide el tamaño de los arrays, la función devuelve **`None`**.

Se agregará al comienzo de la función un **`docstring`** de ayuda con la información de lo que hace la función, de los parámetros que recibe y de lo que devuelve. 

In [ ]:
def suma_ponderada(array1, array2, peso1, peso2):
    # Agregar un docstring a la función.
    # El docstring se hará en formato "numpy"
    """  
    Descripción: COMPLETAR

    Entradas: COMPLETAR
    -
    -
    -
    -

    Salida: COMPLETAR
    -
    """

    # COMPLETAR El código de la función

    return resultado

In [ ]:
# Ver descripción de la función usando shift-tab con el cursor dentro de los paréntesis
suma_ponderada()

In [ ]:
# Probar la función con los siguientes arreglos
A = np.arange(10)
B = np.arange(20)

# Verificar el control de tamaño de arrays
C = suma_ponderada(A, B, 0.3, 0.7)
print(f'{C=}')

# Usar la función
D = suma_ponderada(A, B[::2], 0.3, 0.7)
print(f'{D=}')

## Parte 6 - Cargar datos y uso de librería Pandas
Existen diversas librerías para cargar datos desde archivos, acá proponemos usar la librería pandas para ello. También se puede usar numpy, pero pandas es más potente. 

#### 6.1 Cargar datos

Usar la función `pd.read_csv(...)` del módulo **pandas** para leer los datos  del archivo ``iris_dataset.csv`` en un [**dataframe**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html). 

El [conjunto de Flores Iris](https://en.wikipedia.org/wiki/Iris_flower_data_set) consiste en una pequeña base de datos (ya consolidada en ciencia de datos) que contiene un registro de 150 flores de tres especies distintas (_setosa, versicolor y virginica_). Para cada flor incluye su largo y ancho tanto para pétalo como el sépalo y a qué especie pertenece.

In [ ]:
# Indicar camino del archivo CSV a levantar
csv_path = './iris_dataset.csv'

iris_df = pd.read_csv(csv_path)

#### 6.2 Análisis de datos

Analizar el conjunto de datos usando los métodos `info(), describe(), head() y tail()`. Obtener a partir del *dataframe* un array de *numpy*. 

Puede usar [este enlace](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) como referencia para los distintos métodos o _Shift+Tab_.

In [ ]:
# Información general del dataframe
iris_df.info()

In [ ]:
# Mostrar los primeros n valores del dataframe
# Abrir el CSV en una hoja de cálculo y verificar que coincidan
iris_df.head(n=5)

In [ ]:
# Mostrar últimos n valores del dataframe
# Abrir el CSV en una hoja de cálculo y verificar que coincidan
iris_df.tail(n=5)

In [ ]:
# Mostrar descripciones generales del dataframe
iris_df.describe()

¿Cuál es su valor medio por cada una de las características?

_Respuesta_:
- sepal length : X cm
- sepal width  : X cm
- petal length : X cm
- petal width  : X cm 

#### 6.3 Otras propiedades de `Dataframes`

Obtener un arreglo numpy a partir del dataframe. ¿Qué pasó con las columnas?

In [ ]:
# Array de numpy
iris_np = # COMPLETAR
# Imprimir array
print(iris_np)

Indicar cuántas flores hay con el **largo del pétalo mayor a 2.9 cm**

In [ ]:
cantidad_flores = # COMPLETAR

print(f'Hay {cantidad_flores} flores con largo de pétalo mayor a 2.9 cm')

Graficar con `subplots` el histograma de cada columna del dataframe.


In [ ]:
# COMPLETAR: subplots con histogramas

## Parte 7 - Pandas con Series Temporales

#### 7.1 Cargar datos y uso de [pd.Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)
Cargar los datos `serie_temporal.csv` y volver a ver las estadísticas como en la **parte 6.2**.

In [ ]:
# Indicar camino del archivo CSV a levantar
csv_path = "serie_temporal.csv"

# Cargar los datos indicando que la primer columna corresponde al índice temporal
df = pd.read_csv(csv_path,index_col=0)

index_old = df.index

# Establecer indice al tipo Datetime de pandas
df.index = pd.DatetimeIndex(df.index)

# Información general de dataframe
df.info()

In [ ]:
# Pasar de dataframe a serie
df = df.squeeze()
# Información general de serie
df.info()

In [ ]:
# Mostrar los primeros n valores de la serie
df.head(n=5)

In [ ]:
# Mostrar los primeros n valores de la serie
df.tail(n=5)

In [ ]:
# Mostrar descripciones generales
df.describe()

#### 7.2 Graficar serie

In [ ]:
# Graficar los datos
plt.figure(figsize=(15,2)) # Ajustar tamaño de gráfica
# COMPLETAR: graficar (función incorporada o "método" del objeto dataframe)
plt.show()

#### 7.3 Indexado de la serie

Indexar la serie de pandas de manera que se quede con los meses de Septiembre, Octubre y Noviembre de 2010. 

Graficar en el tiempo cada mes.

In [ ]:
# Extraer mes de Septiembre 
df_sept = # COMPLETAR

# Extraer mes de Noviembre usando las fechas como indices
df_nov = # COMPLETAR

# Concatenar ambos estos dos dataframes (primero septiembre y luego noviembre) y graficar
df_sept_nov = # COMPLETAR: usar pd.concat()
df_sept_nov.index = np.arange(len(df_sept_nov)) # Arreglar indices

#### 7.4 Operaciones en la serie

##### 7.4.1: Calcular los valores promedios en cada mes obtenido en 7.3

In [ ]:
# Calcular los promedios de cada mes
df_sept_mean = # COMPLETAR
print('Potencia promedio del mes de Septiembre:', df_sept_mean)

df_oct_mean = # COMPLETAR
print('Potencia promedio del mes de Octubre:', df_oct_mean)

df_nov_mean = # COMPLETAR
print('Potencia promedio del mes de Noviembre:', df_nov_mean)

##### 7.4.2: Uso de [_rolling en series_](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html) (ventanas deslizante)

Graficar junto a la serie, usando ventantas deslizantes ( _df.rolling()_ ) de N=100 muestras:
 - su valor promedio
 - su valor mínimo
 - su valor máximo

In [ ]:
# Cantidad de muestras
N = 100

# Objeto con todas las ventanas de la serie
df_win = df.rolling(N)

plt.figure(figsize=(15,3))
df.plot()
# COMPLETAR: aplicar y graficar media móvil
# COMPLETAR: aplicar y graficar mínima móvil
# COMPLETAR: aplicar y graficar máxima móvil
plt.legend(['Serie','Media','Mínimo','Máximo'])
plt.grid()
plt.show()


EXPERIMENTAR: graficar para distintos valores de $N$ (50, 200, 500)

## Parte 8 - Detección simple de "anomalias"

Calcular la media y la desviación estándar de los datos del mes de noviembre. Indicar en **toda la serie** cuándo los datos se apartan 3 desviaciones estándar de la media. Representar gráficamente estos eventos.

In [ ]:
mean_nov = df_nov.mean() # COMPLERTAR: calcular media del mes de Noviembre
std_nov = df_nov.std() # COMPLERTAR: calcular desviación estándar del mes de Noviembre

# Quedarse con los elementos de toda la serie que satisfacen la definición de anomalía
anomalias = # COMPLETAR
anomalias.name = 'Anomalías'

# Graficar anomalías como puntos ('*') usar matplotlib

plt.figure(figsize=(15,4))

# COMPLETAR: graficar toda la serie

# COMPLETAR: graficar anomalías

plt.show()
